apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-ingress-v2-0
  namespace: release-v2-0
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /app/v2-0(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: flask-service-v2-0
                port:
                  number: 80
